workflow:
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "external_pull_request_event"
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH

stages:
  - verify

default:
  image: node:20
  variables:
    CI: "true"
  cache:
    key:
      files:
        - client/package-lock.json
        - server/package-lock.json
    paths:
      - client/node_modules/
      - server/node_modules/
    policy: pull-push

frontend:lint:
  stage: verify
  script:
    - npm ci --prefix client
    - npm run --prefix client lint

frontend:test:
  stage: verify
  script:
    - npm ci --prefix client
    - npm run --prefix client test

backend:lint:
  stage: verify
  script:
    - npm ci --prefix server
    - npm run --prefix server lint

backend:test:
  stage: verify
  script:
    - npm ci --prefix server
    - mkdir -p server/config && [ -f server/config/.env.test ] || touch server/config/.env.test
    - npm run --prefix server test