version: '3.8'

services:
  # PostgreSQL Database for development
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: dripiq_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Redis for development
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data

  # Development server (with hot reload)
  server-dev:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/dripiq_dev
      - REDIS_URL=redis://redis:6379
      - PORT=8080
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
      - /app/node_modules
      - /app/dist
    depends_on:
      - postgres
      - redis
    command: npm run dev

  # Development client (with hot reload)
  client-dev:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    environment:
      - VITE_API_URL=http://localhost:8080
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/dist
    command: npm run dev

volumes:
  postgres_dev_data:
  redis_dev_data: