export const schema = {
  type: 'object',
  properties: {
    PORT: { type: 'string' },
    API_VERSION: { type: 'string' },
    CREDENTIALS: { type: 'string' },
    FRONTEND_ORIGIN: { type: 'string' },
    DATABASE_URL: { type: 'string' },
    STRIPE_API_KEY: { type: 'string' },
    STRIPE_SUBSCRIPTION_WEBHOOK_SECRET: { type: 'string' },
    STRIPE_PRICE_ID: { type: 'string' },
    API_URL: { type: 'string' },
    PLAID_CLIENT_ID: { type: 'string' },
    PLAID_SECRET: { type: 'string' },
    NODE_ENV: { type: 'string' },
    DB_SCHEMA: { type: 'string' },
    REDIS_URL: { type: 'string' },
    BULLMQ_PREFIX: { type: 'string' },
  },
  required: ['PORT', 'NODE_ENV', 'REDIS_URL', 'FRONTEND_ORIGIN'],
} as const;
