# Force HTTPS and canonical apex domain
[[redirects]]
  from = "http://dripiq.ai/*"
  to = "https://dripiq.ai/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.dripiq.ai/*"
  to = "https://dripiq.ai/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.dripiq.ai/*"
  to = "https://dripiq.ai/:splat"
  status = 301
  force = true

# Redirect Netlify subdomains to apex
[[redirects]]
  from = "https://dripiq-landing.netlify.app/*"
  to = "https://dripiq.ai/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://dripiq-landing.netlify.app/*"
  to = "https://dripiq.ai/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://dripiq-landing.netlify.app/*"
  to = "https://dripiq.ai/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://dripiq-landing.netlify.app/*"
  to = "https://dripiq.ai/:splat"
  status = 301
  force = true

# Optional: trailing slash policy (choose one)
# This forces trailing slash
# [[redirects]]
#   from = "/:path"
#   to = "/:path/"
#   status = 301
#   force = true

# SPA fallback must come last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Default headers for all files
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "max-age=3600"

# Caching policy for versioned assets
[[headers]]
  for = "/static/js/*"
  [headers.values]
    Cache-Control = "max-age=31536000, immutable"

[[headers]]
  for = "/static/css/*"
  [headers.values]
    Cache-Control = "max-age=31536000, immutable"

# Caching for images and other assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "max-age=86400"
