name: Daily Deploy to Render

on:
  schedule:
    # Runs every day at 2:00 AM Central Time (7:00 AM UTC)
    - cron: '0 7 * * *'
  workflow_dispatch: # Allow manual triggering for testing

jobs:
  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    
    steps:
      - name: Trigger Render Deploy Hook
        run: |
          echo "Triggering Render deployment..."
          response=$(curl -s -w "HTTP_STATUS:%{http_code}" -X POST "${{ secrets.RENDER_DEPLOY_URL }}")
          http_status=$(echo "$response" | grep -o "HTTP_STATUS:[0-9]*" | cut -d: -f2)
          
          if [[ "$http_status" -ge 200 && "$http_status" -lt 300 ]]; then
            echo "✅ Deploy hook triggered successfully (HTTP $http_status)"
          else
            echo "❌ Deploy hook failed (HTTP $http_status)"
            echo "Response: $response"
            exit 1
          fi